### ISSUE TITLE
models.DesiredLRPUpdate missing PlacementTags field

### ISSUE THREAD

**Issue by ScarletTanager** [cloudfoundry/bbs#10]
models.DesiredLRPUpdate is missing the PlacementTags field - without this, moving apps between isolation segments will not work correctly.

**Comment by ScarletTanager** [comment]
We are going to work on a PR to fix this @ematpl .  Ping if you have questions or concerns, @andrew-edgar walked me through the relevant portions of the code.

**Comment by ematpl** [comment]
Hi, @ScarletTanager,

I'm not sure what @andrew-edgar talked to you about, but currently it wouldn't be possible to modify the placement tags on an existing DesiredLRP. The fields that you can update today on a DesiredLRP are all ones that have no effect on the LRP instances that would still remain after the update: changing `Routes` or `Annotation` has no effect, as they are purely metadata, and changing `Instances` could create new instances or destroy existing ones but would result in no change to remaining ones. Everything else on the DesiredLRP affects either the placement or the execution (or both) of all the instances. For Diego to respect a change to one of those fields, it would have to stop all the existing instances and restart them with the updated definition, so we don't currently support those kinds of updates. Placement tags definitely fall into that category: if they are updated, all the instances of that LRP would need to be stopped and re-scheduled onto other cells that match the new placement criteria.

At the moment, the way for a client to handle such a change is to create a new DesiredLRP with the updated definition and to delete the old one. We realize that that client-side complexity is less than ideal, and we intend to introduce an extension to the BBS API to allow the entire LRP definition to be updated, with Diego doing a rolling update of the LRP instances to converge to the new definition. We have already produced an [initial proposal for this extension](https://github.com/cloudfoundry/diego-dev-notes/blob/master/proposals/desired_lrp_update_API.md), and it will be one of the topics the team incepts on in a few weeks, although we do need some feedback from the CAPI team about how they would change their logic to adopt the new capability optimally (for example, they would likely want to start using the v2 app guid or v3 process guid as the identifier for the DesiredLRP once it is mutable, instead of the current app-guid-app-version-guid concatenation).

Thanks,
Eric

**Comment by ematpl** [comment]
I'm going close this out, but we'll plan eventually to have support for updating placement tags via a more comprehensive and holistic notion of updates to DesiredLRPs.
