### ISSUE TITLE
Possible goroutine leak in BBS

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry/bbs#20]
When we have been running the BBS for a long time.  The metric showing the number of goroutines seems to continue to grow.  This is especially true when doing a deployment and rolling all the cells.

We are testing with with 1.18.1 of Diego.

I have attached 2 goroutine.out dumps from our system.  The key ones to look at are those that are in IO wait state for more than 1 minute (in fact there are many over 30 minutes).

I feel this might be an issue in "ifrit" as the http_server we use never sets the READ_TIMEOUT or WRITE_TIMEOUT.  It might be a good idea to timeout those long waiting goroutines to clean things up.

[bbs.zip](https://github.com/cloudfoundry/bbs/files/1121950/bbs.zip)
![image](https://user-images.githubusercontent.com/12702547/27829190-8c820276-60c0-11e7-86b8-7b28639e03a0.png)

The image is the bbs.numGoRoutines.  You can see the growth during a deployment and during a higher limit but there is also a slight climb in the number as time passes.

Let me know if you require any additional information.

Thanks!

Andrew Edgar

**Comment by andrew-edgar** [comment]
I did a little more investigation and drilled down to the "workpool"  I see in the BBS that in a few places we set that we have 1000 workers in a workpool.  I was drilling into the code and wanted a little clarification or validation in the code in workpool/workpool.go:110

Looking at the goroutines.out I posted before there are at least 1000 of these workers just sitting at the select.   But why so many if they should be idle?

I looked here https://github.com/cloudfoundry/workpool/blob/0e2024d2a925068519f6ba470d11f8b735ecd4f4/workpool.go#L141 and I'm not sure this line can be reached in this loop.  Can you confirm?

Plus this workpool looks like it will never shrink.  So this explains the slow but gradual increase in goroutines that are not really required.   I also never saw any tests in the workpool repo to test idleWorkers and if there are idle workers what happens when new work is added.

Thanks

Andrew

**Comment by ematpl** [comment]
Hey, @andrew-edgar, thanks for looking into the goroutine usage and the logic in the workpool. The line at https://github.com/cloudfoundry/workpool/blame/0e2024d2a925068519f6ba470d11f8b735ecd4f4/workpool.go#L141 can indeed be reached, as the worker processing will `break` out of the `NOWORK`-labeled for loop when the work queue is empty (or when the workpool is stopping) and then proceed to that line after claiming the lock.

That said, I think there are larger problems with the worker idling and contraction logic in the workpool. Because `w.idleWorkers` is always decremented before it is incremented, it can never become positive, so the first condition in https://github.com/cloudfoundry/workpool/blob/0e2024d2a925068519f6ba470d11f8b735ecd4f4/workpool.go#L66 is always false. If it's to be useful as it seems to have been intended, it seems like `addWorker` should increment the idle-worker count (since the worker starts out idle) and `workerStopping` should decrement it.

The idle-worker count is really just an optimization not to create new workers unnecessarily when new work comes in, though. I think the real issue with worker contraction is that the inequality direction on https://github.com/cloudfoundry/workpool/blob/0e2024d2a925068519f6ba470d11f8b735ecd4f4/workpool.go#L78 is reversed. Right now, it says that the worker should not stop (`return false`) if the work queue size is less than or equal to the number of workers, but that means the worker should stop only when the work queue length is greater than the number of workers, which seems wrong. Instead, it should be that the worker stops with the work queue length is less than the number of workers, so the inequality should check whether the work queue length is greater than or equal to the number of workers and only then not stop a worker. Of course, we should make sure that any changes still avoid the problem on https://www.pivotaltracker.com/n/projects/1003146/stories/119057201 where the route-emitter was hanging on sync because of some edge case over worker contraction.

In any case, we'll prioritize this for the Diego team to look into. You're also right that there's no test coverage for the worker contraction behavior, so it may make sense to add that.

Thanks,
Eric

**Comment by andrew-edgar** [comment]
@ematpl that's almost exactly what I was just about to write.  I did a small test to print when the value was incremented and decremented and yes it's definitely wrong.   With the maxworkers set to 1000 in a couple places in the BBS this meant we would build up to 2000 threads essentially mostly doing nothing but a busy loop looking for work on a timer.  

Thanks for looking into that as I was going to write a test but if you guys have it then that's perfect.

Andrew

**Comment by ematpl** [comment]
Thanks, @andrew-edgar ! To be fair, it shouldn't be any kind of performance concern to keep a few thousand extra goroutines around, especially if they're mostly just parked, although it is a minor distraction to see the inflated goroutine count and noise in the goroutine dump.

I'd also be interested to see if there are any performance issues related to stopping worker goroutines on too short of a time scale. Those goroutines are currently configured to be cleaned up after being idle for 5 seconds, but I could see that resulting in always contracting the workers to 0 for the BBS convergence and then creating a new set of workers when it has more convergence work to do. It would potentially be interesting to determine whether there's more of a performance hit from that kind of thrash than from simply keeping that pool of idle goroutines around.

In any case, there's certainly at least some clean-up to do here in the codebase, and we'll have the team discuss the behavioral direction we want to take.

Thanks again,
Eric

**Comment by andrew-edgar** [comment]
I see there was an update to remove the contraction in the workpool code.  Has this been pulled into diego yet?

**Comment by emalm** [comment]
Hi, @andrew-edgar,

Yes, the removal should be part of Diego v1.23.1 and later. Sorry for leaving the GitHub issue dangling!

Best,
Eric
