### ISSUE TITLE
Diego::Bbs::Models::TimeoutAction#deprecated_timeout_ns= field usage is deprecated

### ISSUE THREAD

**Issue by sharms** [cloudfoundry/bbs#25]
When running Diego we receive hundreds of messages in the format of:

```
[2017-12-16 08:57:06+0000] DEPRECATION WARNING: Diego::Bbs::Models::TimeoutAction#deprecated_timeout_ns= field usage is deprecated. (called from protobuf_decode! at /var/vcap/data/packages/cloud_controller_ng/redacted/cloud_c
ontroller_ng/lib/diego/client.rb:177)
[2017-12-16 08:57:08+0000] DEPRECATION WARNING: Diego::Bbs::Models::DesiredLRP#deprecated_start_timeout_s= field usage is deprecated. (called from protobuf_decode! at /var/vcap/data/packages/cloud_controller_ng/redacted/cloud
_controller_ng/lib/diego/client.rb:177)
```

**Comment by emalm** [comment]
Hi, @sharms,

Thanks for reporting this issue. Those fields are indeed deprecated on those protobuf messages, so the warning isn't wrong, but I can see that the log noise is a problem. From the error messages you supplied, this issue seems like it originates in Cloud Controller, in its BBS client library, but the client models were likely generated following [this section](https://github.com/cloudfoundry/bbs#generating-ruby-models-for-bbs-models) in the BBS repo README. @zrob and @gerg, do you think it'd be more appropriate for the CAPI team to evaluate this issue? /cc @jvshahid 

Thanks,
Eric, CF Diego PM

**Comment by charleshansen** [comment]
@emalm I just took a crack at fixing this on the CAPI side. CAPI isn't sending these deprecated fields to BBS, but the BBS is responding to CAPI with those fields (most notably when we create a staging task). When we decode the BBS response, we get the deprecation warning. 
https://github.com/cloudfoundry/cloud_controller_ng/blob/f502f8f5c051b7f95c9a92f26987ddb442af374d/lib/diego/client.rb#L177

I'm not 100% sure what the best way to do this is, but it feels weird to mark a proto field as deprecated and then send the field in the response even though we never gave it in the request. I may be able to shim in a fix to suppress the warnings on decode, but this does not seem ideal (I don't want to suppress warnings on encoding, because that would mean CAPI is actually sending deprecated fields). Are there other approaches here I am missing?

**Comment by charleshansen** [comment]
Talked to the team some, decided to just turn off the warning messages entirely https://github.com/cloudfoundry/cloud_controller_ng/commit/bef5906b390e4309d68be352ddaf9993da3c8cfa

**Comment by charleshansen** [comment]
The two big offenders were in the original issue `TimeoutAction#deprecated_timeout_ns` and `DesiredLRP#deprecated_start_timeout_s`.

We are somewhat protected from other issues because we haven't recompiled the proto in a while (and currently cant https://github.com/cloudfoundry/bbs/issues/34). There are some new deprecated fields that will also cause issues. I did compile the proto by hand the other day. I didn't run a full cats or anything, but I did see `DesiredLRP#legacy_download_user` pop up pretty quick.

For a little more nuance, I do still think BBS is somehow handling the deprecations non-optimally, but the ruby proto2 client is really at fault. It should print the deprecation warnings in a more lazy fashion, waiting until we access the fields (which we never do) instead of warning as soon as we get deprecated fields from BBS. This is partially why we thought it was ok to just suppress the warnings. If you can improve the deprecated field situation for BBS by using a pointer, I'm all for it, but don't go out of your way for CAPI here.

**Comment by heyjcollins** [comment]
As this item has been open for quite a long time, I'm going to go ahead and close it.
