### ISSUE TITLE
SSH Private Key logged

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/bbs#8]
This is with CF 234.  Here is an example log message:  
```
{"timestamp":"1467146807.864567757","source":"bbs","message":"bbs.desired-lrp-handler.update-desired-lrp.update-desired-lrp.complete","log_level":1,"data":{"guid":"0dad3416-9769-4c4c-a0b6-98d379df33bf-ddb6e26f-3c55-40fe-b2a5-714ac9b3c466","process-guid":"0dad3416-9769-4c4c-a0b6-98d379df33bf-ddb6e26f-3c55-40fe-b2a5-714ac9b3c466","session":"6.49043.1","update":{"instances":1,"routes":{"cf-router":[{"hostnames":["--deleted--","--deleted--","--deleted--"],"port":8080}],"diego-ssh":{"container_port":2222,"host_fingerprint":"--deleted--","private_key":"-----BEGIN RSA PRIVATE KEY-----\nSOME PRIVATE KEY\n-----END RSA PRIVATE KEY-----\n"},"tcp-router":[]},"annotation":"1467146790.0"}}}
```

**Comment by ematpl** [comment]
Thanks, @youngm! Looks like we fixed this in https://github.com/cloudfoundry/bbs/commit/b1499ed978a7535df00cac3d20a39ef3e23b90c7, which is in Diego release [v0.1468.0](https://github.com/cloudfoundry/diego-release/releases/tag/v0.1468.0). I would recommend using [v0.1471.0](https://github.com/cloudfoundry/diego-release/releases/tag/v0.1471.0) or later instead of that release, though, as v0.1468.0 contains a serious vulnerability.

Also, seems like we no longer have the correct Gitbot integrations established after moving the Diego repos into the cloudfoundry org. We'll make sure to fix that ASAP.

Thanks again,
Eric

**Comment by youngm** [comment]
@ematpl Oops.  That was lazy of me. :)  Sorry about that.

You're awesome!

**Comment by ematpl** [comment]
Thanks for being diligent about credentials in logs, Mike! We always appreciate it.

Best,
Eric
